In [42]:
import pandas as pd
import numpy as np

In [2]:
df2021 = pd.read_csv("accident2021.csv", encoding="utf-8-sig")
df2022 = pd.read_csv("accident2022.csv", encoding="utf-8-sig")
df2023 = pd.read_csv("accident2023.csv", encoding="utf-8-sig")
df2024 = pd.read_csv("accident2024.csv", encoding="utf-8-sig")
df2025 = pd.read_csv("accident2025.csv", encoding="utf-8-sig")

In [3]:
files = {
    "2021": df2021,
    "2022": df2022,
    "2023": df2023,
    "2024": df2024,
    "2025": df2025
}

for year, df in files.items():
    print(f"\n===== {year} =====")
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

===== 2021 =====
Rows: 20062
Columns: 38

===== 2022 =====
Rows: 20566
Columns: 38

===== 2023 =====
Rows: 23841
Columns: 38

===== 2024 =====
Rows: 23952
Columns: 38

===== 2025 =====
Rows: 23715
Columns: 38

In [4]:
accident_all = pd.concat([df2021, df2022, df2023, df2024, df2025],
    ignore_index=True
)

In [5]:
print("จำนวนแถว:", accident_all.shape[0])
print("จำนวนคอลัมน์:", accident_all.shape[1])

จำนวนแถว: 112136
จำนวนคอลัมน์: 38

In [6]:
accident_all.to_csv("accident_all.csv",index=False,encoding="utf-8-sig")

In [7]:
accident_all.isnull().sum()

ปีที่เกิดเหตุ               0
วันที่เกิดเหตุ              0
เวลา                        0
วันที่รายงาน                4
เวลาที่รายงาน               8
ACC_CODE                    0
หน่วยงาน                    0
สายทางหน่วยงาน              0
รหัสสายทาง                 12
สายทาง                  22169
KM                        917
จังหวัด                  1952
รถคันที่1                1717
บริเวณที่เกิดเหตุ        9341
มูลเหตุสันนิษฐาน         2170
ลักษณะการเกิดเหตุ        6202
สภาพอากาศ                 744
LATITUDE                  721
LONGITUDE                 721
รถที่เกิดเหตุ               0
รถและคนที่เกิดเหตุ          0
รถจักรยานยนต์               0
รถสามล้อเครื่อง             0
รถยนต์นั่งส่วนบุคคล         0
รถตู้                       0
รถปิคอัพโดยสาร              0
รถโดยสารมากกว่า4ล้อ         0
รถปิคอัพบรรทุก4ล้อ          0
รถบรรทุก6ล้อ                0
รถบรรทุกไม่เกิน10ล้อ        0
รถบรรทุกมากกว่า10ล้อ        0
รถอีแต๋น                    0
รถอื่นๆ                     0
คนเดินเท้า                  0
ผู้เสียชีวิต                0
ผู้บาดเจ็บสาหัส             0
ผู้บาดเจ็บเล็กน้อย          0
รวมจำนวนผู้บาดเจ็บ          0
dtype: int64

In [8]:
print("Duplicate:", accident_all.duplicated().sum())

Duplicate: 61

In [9]:
for col in accident_all.columns:
    print(col)

ปีที่เกิดเหตุ
วันที่เกิดเหตุ
เวลา
วันที่รายงาน
เวลาที่รายงาน
ACC_CODE
หน่วยงาน
สายทางหน่วยงาน
รหัสสายทาง
สายทาง
KM
จังหวัด
รถคันที่1
บริเวณที่เกิดเหตุ
มูลเหตุสันนิษฐาน
ลักษณะการเกิดเหตุ
สภาพอากาศ
LATITUDE
LONGITUDE
รถที่เกิดเหตุ
รถและคนที่เกิดเหตุ
รถจักรยานยนต์
รถสามล้อเครื่อง
รถยนต์นั่งส่วนบุคคล
รถตู้
รถปิคอัพโดยสาร
รถโดยสารมากกว่า4ล้อ
รถปิคอัพบรรทุก4ล้อ
รถบรรทุก6ล้อ
รถบรรทุกไม่เกิน10ล้อ
รถบรรทุกมากกว่า10ล้อ
รถอีแต๋น
รถอื่นๆ
คนเดินเท้า
ผู้เสียชีวิต
ผู้บาดเจ็บสาหัส
ผู้บาดเจ็บเล็กน้อย
รวมจำนวนผู้บาดเจ็บ

In [10]:
sorted(accident_all["จังหวัด"].dropna().unique())

['กระบี่',
 'กรุงเทพมหานคร',
 'กาญจนบุรี',
 'กาฬสินธุ์',
 'กำแพงเพชร',
 'ขอนแก่น',
 'จันทบุรี',
 'ฉะเชิงเทรา',
 'ชลบุรี',
 'ชัยนาท',
 'ชัยภูมิ',
 'ชุมพร',
 'ตรัง',
 'ตราด',
 'ตาก',
 'นครนายก',
 'นครปฐม',
 'นครพนม',
 'นครราชสีมา',
 'นครศรีธรรมราช',
 'นครสวรรค์',
 'นนทบุรี',
 'นราธิวาส',
 'น่าน',
 'บึงกาฬ',
 'บุรีรัมย์',
 'ปทุมธานี',
 'ประจวบคีรีขันธ์',
 'ปราจีนบุรี',
 'ปัตตานี',
 'พะเยา',
 'พังงา',
 'พัทลุง',
 'พิจิตร',
 'พิษณุโลก',
 'ภูเก็ต',
 'มหาสารคาม',
 'มุกดาหาร',
 'ยะลา',
 'ยโสธร',
 'ระนอง',
 'ระยอง',
 'ราชบุรี',
 'ร้อยเอ็ด',
 'ลพบุรี',
 'ลำปาง',
 'ลำพูน',
 'ศรีสะเกษ',
 'สกลนคร',
 'สงขลา',
 'สตูล',
 'สมุทรปราการ',
 'สมุทรสงคราม',
 'สมุทรสาคร',
 'สระบุรี',
 'สระแก้ว',
 'สิงห์บุรี',
 'สุพรรณบุรี',
 'สุราษฎร์ธานี',
 'สุรินทร์',
 'สุโขทัย',
 'หนองคาย',
 'หนองบัวลำภู',
 'อยุธยา',
 'อำนาจเจริญ',
 'อุดรธานี',
 'อุตรดิตถ์',
 'อุทัยธานี',
 'อุบลราชธานี',
 'อ่างทอง',
 'เชียงราย',
 'เชียงใหม่',
 'เพชรบุรี',
 'เพชรบูรณ์',
 'เลย',
 'แพร่',
 'แม่ฮ่องสอน']

In [11]:
accident_all["สภาพอากาศ"].value_counts(dropna=False)

สภาพอากาศ
แจ่มใส                           97031
ฝนตก                             13537
NaN                                744
มีหมอก/ควัน/ฝุ่น                   392
มืดครึ้ม                           297
อื่นๆ                               79
ภัยธรรมชาติ เช่น พายุ น้ำท่วม       56
Name: count, dtype: int64

In [12]:
accident_all["มูลเหตุสันนิษฐาน"].value_counts(dropna=False)

มูลเหตุสันนิษฐาน
ขับรถเร็วเกินอัตรากำหนด         64494
ขับรถเร็วเกินอัตราที่กำหนด      14636
หลับใน                           7712
คน/รถ/สัตว์ตัดหน้ากระชั้นชิด     6680
NaN                              2170
                                ...
ระบบไฟขัดข้องในห้องเครื่อง          1
ขับขี่ย้อนศร                        1
ระบบบังขับเลี้ยวชำรุด               1
ฝาตู้เก็บของด้านข้างเปิด            1
เบรคกะทันหัน                        1
Name: count, Length: 117, dtype: int64

In [13]:
accident_all["มูลเหตุสันนิษฐาน"] = accident_all["มูลเหตุสันนิษฐาน"].replace({

    "ขับขี่ย้อนศร": "ขับรถย้อนศร",

    "ขับชิดซ้ายมากเกินไป": "ขับรถชิดซ้ายมากเกินไป",

    "ขับรถกระชั้นชิด": "ขับรถตามกระชั้นชิด",

    "ฝ่าฝืนสัญญาณไฟ / เครื่องหมายจราจร": "ฝ่าฝืนสัญญาณไฟ/เครื่องหมายจราจร",

    "ฝ่าฝืนป้ายหยุดขณะออกจากทางร่วมทางแยก": "ฝ่าฝืนป้ายหยุดขณะออกจากทางร่วมแยก",

    "มึนเมาจากแอลกอฮอล์": "เมาสุรา",

    "รถเสียไม่แสดงเครื่องหมาย/สัญญาณตามที่กำหนด":
        "รถเสียไม่แสดงเครื่องหมายหรือสัญญาณไฟที่กำหนด",

    "ระบบไฟฟ้ขัดข้อง": "ระบบไฟฟ้าขัดข้อง",
    "ระบบไฟฟ้าของยานพาหนะขัดข้อง": "ระบบไฟฟ้าขัดข้อง",

    "อาการป่วย หรือการไร้ความสามารถทางประสาทหรือร่างกาย":
        "อาการป่วยหรือการไร้ความสามารถทางประสาทหรือร่างกาย",

    "ใช้โทรศัพท์เคลื่อนที่ขณะขับรถ": "ใช้โทรศัพท์ขณะขับรถ",

    "ไม่ให้สัญญาณชะลอ / เลี้ยว": "ไม่ให้สัญญาณชะลอ/เลี้ยว",

    "ไม่ให้สัญญาณเข้าจอด หรือออกจากที่จอด":
        "ไม่ให้สัญญาณเข้าจอด/ออกจากที่จอด",

    "ไม่คุ้นเคยกับการขับขี่ด้านซ้าย เช่น กรณีชาวต่างชาติ":
        "ไม่คุ้นเคยกับการขับขี่ด้านซ้าย",

    "เบรคกะทันหัน": "เบรกกะทันหัน",
    
    "เบรคกระทันหัน": "เบรกกะทันหัน",
    
    "เบครกระทันหัน": "เบรกกะทันหัน",

    "ถนนลื่น (เนื่องจากสภาพอากาศ)": "ถนนลื่น",

    "มีสิ่งรบกวนภายในรถ เช่น มีเด็ก มีสัตว์ภายในรถ":
        "มีสิ่งรบกวนภายในรถ",

    "แสงสว่างไม่เพียงพอหรือทัศนวิสัยกลางคืนไม่ดี":
        "แสงสว่างไม่เพียงพอ",

    "เข้าผิดช่องทางผิด": "เข้าผิดช่อง",

    "ไม่คุ้นชินกับยานพาหนะ เช่น กรณีเช่ารถ":
        "ไม่คุ้นเคยเส้นทาง/ขับรถไม่ชำนาญ"
})

In [14]:
accident_all["มูลเหตุสันนิษฐาน"] = accident_all["มูลเหตุสันนิษฐาน"].replace({
  
     "อุปกรณ์ยานพาหนะบกพร่อง (ระบุ)": "อุปกรณ์ยานพาหนะบกพร่อง"
})

In [15]:
for value in sorted(accident_all["มูลเหตุสันนิษฐาน"].dropna().unique()):
    print(value)

การกระทำที่สุ่มเสี่ยงบนถนน
การซ่อม/สร้างบนสายทาง
กำลังเครื่องยนต์ไม่เพียงพอ
ขับขี่ช้าเกินเนื่องจากลักษณะของยานพาหนะ (เช่น แทรคเตอร์)
ขับชิดขอบทางขวามากเกินไป
ขับรถคร่อมเส้นแบ่งทิศทาง
ขับรถชิดขวามากไป
ขับรถชิดซ้ายมากเกินไป
ขับรถช้าลง
ขับรถตามกระชั้นชิด
ขับรถผิดช่องทาง
ขับรถย้อนศร
ขับรถเร็วเกินอัตรากำหนด
ขับรถเร็วเกินอัตราที่กำหนด
ขับรถไม่ชำนาญ / ไม่เป็น
ขับรถไม่เปิดไฟ / ไม่ใช้แสงสว่างตามกำหนด
ขับรถไม่เปิดไฟ/ไม่ใช้แสงสว่างตามกำหนด
ข้ามถนนโดยมีรถจอดหรือวัตถุข้างทางบดบังผู้ขับขี่
คน/รถ/สัตว์ตัดหน้ากระชั้นชิด
ความประมาท/เร่งรีบ (วิ่งตัดหน้า)
ความเมื่อยล้า
ถนนชำรุด
ถนนลื่น
ถนนแคบ
ทางโค้งอันตราย
ทำงานบนถนน
นั่งบุคคลขับรถย้อนทิศทางจราจร
บรรทุกสูงเกินกำหนด
บรรทุกเกินอัตรา
ปัญหาทางสายตา
ป้ายจราจรถูกบดบัง
ผิวถนนสภาพแย่หรือชำรุด
ผู้ขับขี่ไม่เห็นเสาไฟส่องสว่าง
ฝาตู้เก็บของด้านข้างเปิด
ฝ่าฝืนป้ายหยุดขณะออกจากทางร่วมแยก
ฝ่าฝืนสัญญาณไฟ/เครื่องหมายจราจร
พวงมาลัยชำรุด
มีกองวัสดุ/สิ่งกีดขวาง
มีการตัดหน้าระยะกระชั้นชิด
มีคราบสะสมบนผิวถนน เช่น โคลน น้ำมัน
มีสิ่งกีดขวางบนทางหลวง (วัสดุหรือสัตว์)
มีสิ่งบดบังการมองเห็น
มีสิ่งรบกวนภายนอก เช่น ป้ายจราจรมีสีที่สว่างเกินไป
มีสิ่งรบกวนภายนอกรถ
มีสิ่งรบกวนภายในรถ
ยางรถยนต์ชำรุด
ยางเสื่อมสภาพ/ยางแตก
ยานพาหนะเคลื่อนที่ช้า
รถมีความสูงเกินกำหนด
รถเสียไม่แสดงเครื่องหมายหรือสัญญาณไฟที่กำหนด
ระบบบังขับเลี้ยวชำรุด
ระบบบังคับเลี้ยวขัดข้อง
ระบบสัญญาณไฟจราจรขัดข้อง
ระบบห้ามล้อขัดข้อง/ระบบเบรกชำรุด
ระบบไฟขัดข้องในห้องเครื่อง
ระบบไฟฟ้าขัดข้อง
ระยะการมองเห็นไม่เพียงพอ
ระยะปลอดภัยข้างทางไม่เพียงพอ
ระยะมองเห็นจำกัด
ละสายตาจากการขับขี่
ลักษณะของถนน เช่น เป็นทางโค้ง, เนินเขา, ผิวทางแคบ
สัญญาณไฟจราจรชำรุด
สูญเสียการควบคุม
หยุดรถกะทันหัน
หลับใน
หางพ่วงหลุด
อาการป่วยหรือการไร้ความสามารถทางประสาทหรือร่างกาย
อื่นๆ
อุปกรณ์ยานพาหนะบกพร่อง
เข้าผิดช่อง
เครื่องยนต์ขัดข้อง
เบรกกะทันหัน
เบรคชำรุด
เปลี่ยนช่องทางกะทันหัน
เมาสุรา
แซงรถอย่างผิดกฎหมาย
แสงสว่างไม่เพียงพอ
โรคประจำตัว
ใช้สารออกฤทธิ์ต่อจิตและประสาท
ใช้โทรศัพท์ขณะขับรถ
ไฟฟ้าแสงสว่างชำรุด
ไฟส่องสว่างชำรุด
ไม่ขับรถในช่องทางเดินรถซ้ายสุดในถนนที่มี 4 ช่องทาง
ไม่คุ้นเคยกับการขับขี่ด้านซ้าย
ไม่คุ้นเคยเส้นทาง/ขับรถไม่ชำนาญ
ไม่มีป้ายจราจร
ไม่มีมูลเหตุสันนิษฐานที่เกี่ยวข้องด้านสภาพสายทาง
ไม่มีระบบสัญญาณไฟจราจร
ไม่มีเส้นแบ่งทิศทางจราจร
ไม่ยอมให้รถที่มีสิทธิ์ไปก่อน
ไม่ให้สัญญาณชะลอ/เลี้ยว
ไม่ให้สัญญาณเข้าจอด/ออกจากที่จอด
ไม่ให้สิทธิรถที่มาก่อนผ่านทาง เช่น ทางแยก

In [16]:
accident_all["ลักษณะการเกิดเหตุ"].value_counts(dropna=False)

ลักษณะการเกิดเหตุ
พลิกคว่ำ/ตกถนนในทางตรง                                  45440
ชนท้าย                                                  34079
พลิกคว่ำ/ตกถนนในทางโค้ง                                 11045
NaN                                                      6202
ชนในทิศทางตรงกันข้าม (ไม่ใช่การแซง)                      4865
                                                        ...
อื่นๆ (เสียหลักรื่่นไถลเข้ามาในช่องทางเดินรถตรงข้าม)        1
อื่นๆ (เสียหลักขับลงข้างทาง)                                1
อื่นๆ (ชนทางเท้า)                                           1
อื่นๆ (กระโปรงเข้าซี่ล้อรถจักรยานยนต์)                      1
อื่นๆ (รถชนคอสะพาน)                                         1
Name: count, Length: 153, dtype: int64

In [17]:
accident_all.isnull().sum()

ปีที่เกิดเหตุ               0
วันที่เกิดเหตุ              0
เวลา                        0
วันที่รายงาน                4
เวลาที่รายงาน               8
ACC_CODE                    0
หน่วยงาน                    0
สายทางหน่วยงาน              0
รหัสสายทาง                 12
สายทาง                  22169
KM                        917
จังหวัด                  1952
รถคันที่1                1717
บริเวณที่เกิดเหตุ        9341
มูลเหตุสันนิษฐาน         2170
ลักษณะการเกิดเหตุ        6202
สภาพอากาศ                 744
LATITUDE                  721
LONGITUDE                 721
รถที่เกิดเหตุ               0
รถและคนที่เกิดเหตุ          0
รถจักรยานยนต์               0
รถสามล้อเครื่อง             0
รถยนต์นั่งส่วนบุคคล         0
รถตู้                       0
รถปิคอัพโดยสาร              0
รถโดยสารมากกว่า4ล้อ         0
รถปิคอัพบรรทุก4ล้อ          0
รถบรรทุก6ล้อ                0
รถบรรทุกไม่เกิน10ล้อ        0
รถบรรทุกมากกว่า10ล้อ        0
รถอีแต๋น                    0
รถอื่นๆ                     0
คนเดินเท้า                  0
ผู้เสียชีวิต                0
ผู้บาดเจ็บสาหัส             0
ผู้บาดเจ็บเล็กน้อย          0
รวมจำนวนผู้บาดเจ็บ          0
dtype: int64

In [18]:
accident_all['LATITUDE'] = pd.to_numeric(accident_all['LATITUDE'], errors='coerce')
accident_all['LONGITUDE'] = pd.to_numeric(accident_all['LONGITUDE'], errors='coerce')

In [19]:
valid_lat = (accident_all['LATITUDE'] >= 5.0) & (accident_all['LATITUDE'] <= 21.0)
valid_long = (accident_all['LONGITUDE'] >= 97.0) & (accident_all['LONGITUDE'] <= 106.0)

In [21]:
accident_all = accident_all[valid_lat & valid_long].copy()

In [22]:
numeric_cols = [
    'รถจักรยานยนต์', 'รถสามล้อเครื่อง', 'รถยนต์นั่งส่วนบุคคล', 'รถตู้',
    'รถปิคอัพโดยสาร', 'รถโดยสารมากกว่า4ล้อ', 'รถปิคอัพบรรทุก4ล้อ', 
    'รถบรรทุก6ล้อ', 'รถบรรทุกไม่เกิน10ล้อ', 'รถบรรทุกมากกว่า10ล้อ', 
    'รถอีแต๋น', 'รถอื่นๆ', 'คนเดินเท้า', 
    'ผู้เสียชีวิต', 'ผู้บาดเจ็บสาหัส', 'ผู้บาดเจ็บเล็กน้อย', 'รวมจำนวนผู้บาดเจ็บ'
]

#แทนที่ค่าว่าง (NaN) ด้วย 0 และแปลงเป็น integer
for col in numeric_cols:
    if col in accident_all.columns:
        accident_all[col] = accident_all[col].fillna(0).astype(int)

print("จำนวน Missing Values ในคอลัมน์ตัวเลข:")
print(accident_all[numeric_cols].isnull().sum())

จำนวน Missing Values ในคอลัมน์ตัวเลข:
รถจักรยานยนต์           0
รถสามล้อเครื่อง         0
รถยนต์นั่งส่วนบุคคล     0
รถตู้                   0
รถปิคอัพโดยสาร          0
รถโดยสารมากกว่า4ล้อ     0
รถปิคอัพบรรทุก4ล้อ      0
รถบรรทุก6ล้อ            0
รถบรรทุกไม่เกิน10ล้อ    0
รถบรรทุกมากกว่า10ล้อ    0
รถอีแต๋น                0
รถอื่นๆ                 0
คนเดินเท้า              0
ผู้เสียชีวิต            0
ผู้บาดเจ็บสาหัส         0
ผู้บาดเจ็บเล็กน้อย      0
รวมจำนวนผู้บาดเจ็บ      0
dtype: int64

In [23]:
text_cols = [
    'บริเวณที่เกิดเหตุ', 'มูลเหตุสันนิษฐาน', 'ลักษณะการเกิดเหตุ', 
    'สภาพอากาศ', 'จังหวัด', 'รถคันที่1', 'สายทาง'
]

for col in text_cols:
    if col in accident_all.columns:
        accident_all[col] = accident_all[col].fillna('ไม่ระบุ').astype(str).str.strip()

In [24]:
accident_all['ชั่วโมง'] = accident_all['เวลา'].astype(str).str.extract(r'(\d+)')[0]
accident_all['ชั่วโมง'] = pd.to_numeric(accident_all['ชั่วโมง'], errors='coerce')

accident_all['ชั่วโมง'] = accident_all['ชั่วโมง'].fillna(-1).astype(int)
#-1 คือการสร้าง Out-of-bound Category หรือ Sentinel Value เพื่อใช้จัดการกับ "ข้อมูลที่ไม่ทราบเวลา / ข้อมูลขยะ"

In [25]:
def clean_time_str(val):
    if pd.isna(val):
        return val
    try:
        v = float(val)
        if 0 <= v <= 1:
            total_sec = int(v * 86400)
            return f"{total_sec // 3600:02d}:{(total_sec % 3600) // 60:02d}"
    except ValueError:
        pass
    return str(val).strip()

accident_all['เวลา'] = accident_all['เวลา'].apply(clean_time_str)
accident_all['ชั่วโมง'] = accident_all['เวลา'].str.extract(r'^(\d{1,2}):')[0]
accident_all['ชั่วโมง'] = pd.to_numeric(accident_all['ชั่วโมง'], errors='coerce')
accident_all['ชั่วโมง'] = accident_all['ชั่วโมง'].fillna(-1).astype(int)

In [26]:
accident_all.isnull().sum()

ปีที่เกิดเหตุ             0
วันที่เกิดเหตุ            0
เวลา                      0
วันที่รายงาน              4
เวลาที่รายงาน             8
ACC_CODE                  0
หน่วยงาน                  0
สายทางหน่วยงาน            0
รหัสสายทาง               10
สายทาง                    0
KM                      354
จังหวัด                   0
รถคันที่1                 0
บริเวณที่เกิดเหตุ         0
มูลเหตุสันนิษฐาน          0
ลักษณะการเกิดเหตุ         0
สภาพอากาศ                 0
LATITUDE                  0
LONGITUDE                 0
รถที่เกิดเหตุ             0
รถและคนที่เกิดเหตุ        0
รถจักรยานยนต์             0
รถสามล้อเครื่อง           0
รถยนต์นั่งส่วนบุคคล       0
รถตู้                     0
รถปิคอัพโดยสาร            0
รถโดยสารมากกว่า4ล้อ       0
รถปิคอัพบรรทุก4ล้อ        0
รถบรรทุก6ล้อ              0
รถบรรทุกไม่เกิน10ล้อ      0
รถบรรทุกมากกว่า10ล้อ      0
รถอีแต๋น                  0
รถอื่นๆ                   0
คนเดินเท้า                0
ผู้เสียชีวิต              0
ผู้บาดเจ็บสาหัส           0
ผู้บาดเจ็บเล็กน้อย        0
รวมจำนวนผู้บาดเจ็บ        0
ชั่วโมง                   0
dtype: int64

In [27]:
(accident_all['หน่วยงาน'].value_counts(dropna=False))

หน่วยงาน
กรมทางหลวง                  103903
กรมทางหลวงชนบท                6037
การทางพิเศษแห่งประเทศไทย      1469
Name: count, dtype: int64

In [28]:
(accident_all['สายทางหน่วยงาน'].value_counts(dropna=False))

สายทางหน่วยงาน
ทางหลวง        103903
ทางหลวงชนบท      6037
การทางพิเศษ      1469
Name: count, dtype: int64

In [29]:
accident_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 111409 entries, 0 to 112135
Data columns (total 39 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ปีที่เกิดเหตุ         111409 non-null  int64
 1   วันที่เกิดเหตุ        111409 non-null  object
 2   เวลา                  111409 non-null  object
 3   วันที่รายงาน          111405 non-null  object
 4   เวลาที่รายงาน         111401 non-null  object
 5   ACC_CODE              111409 non-null  int64
 6   หน่วยงาน              111409 non-null  object
 7   สายทางหน่วยงาน        111409 non-null  object
 8   รหัสสายทาง            111399 non-null  object
 9   สายทาง                111409 non-null  object
 10  KM                    111055 non-null  float64
 11  จังหวัด               111409 non-null  object
 12  รถคันที่1             111409 non-null  object
 13  บริเวณที่เกิดเหตุ     111409 non-null  object
 14  มูลเหตุสันนิษฐาน      111409 non-null  object
 15  ลักษณะการเกิดเหตุ     111409 non-null  object
 16  สภาพอากาศ             111409 non-null  object
 17  LATITUDE              111409 non-null  float64
 18  LONGITUDE             111409 non-null  float64
 19  รถที่เกิดเหตุ         111409 non-null  int64
 20  รถและคนที่เกิดเหตุ    111409 non-null  int64
 21  รถจักรยานยนต์         111409 non-null  int64
 22  รถสามล้อเครื่อง       111409 non-null  int64
 23  รถยนต์นั่งส่วนบุคคล   111409 non-null  int64
 24  รถตู้                 111409 non-null  int64
 25  รถปิคอัพโดยสาร        111409 non-null  int64
 26  รถโดยสารมากกว่า4ล้อ   111409 non-null  int64
 27  รถปิคอัพบรรทุก4ล้อ    111409 non-null  int64
 28  รถบรรทุก6ล้อ          111409 non-null  int64
 29  รถบรรทุกไม่เกิน10ล้อ  111409 non-null  int64
 30  รถบรรทุกมากกว่า10ล้อ  111409 non-null  int64
 31  รถอีแต๋น              111409 non-null  int64
 32  รถอื่นๆ               111409 non-null  int64
 33  คนเดินเท้า            111409 non-null  int64
 34  ผู้เสียชีวิต          111409 non-null  int64
 35  ผู้บาดเจ็บสาหัส       111409 non-null  int64
 36  ผู้บาดเจ็บเล็กน้อย    111409 non-null  int64
 37  รวมจำนวนผู้บาดเจ็บ    111409 non-null  int64
 38  ชั่วโมง               111409 non-null  int64
dtypes: float64(3), int64(22), object(14)
memory usage: 34.0+ MB

In [30]:
accident_all.to_csv('accident_cleaned.csv', index=False, encoding='utf-8-sig')
print("บันทึกไฟล์ accident_cleaned.csv สำเร็จแล้ว!")

บันทึกไฟล์ accident_cleaned.csv สำเร็จแล้ว!

In [31]:
accident_all['วันที่เกิดเหตุ'].tail(10)

112126    46022
112127    46022
112128    46022
112129    46022
112130    46022
112131    46022
112132    46022
112133    46022
112134    46022
112135    46022
Name: วันที่เกิดเหตุ, dtype: object

In [40]:
accident_all['วันที่เกิดเหตุ'].tail(10)

112126   2025-12-31
112127   2025-12-31
112128   2025-12-31
112129   2025-12-31
112130   2025-12-31
112131   2025-12-31
112132   2025-12-31
112133   2025-12-31
112134   2025-12-31
112135   2025-12-31
Name: วันที่เกิดเหตุ, dtype: datetime64[ns]

In [33]:
def parse_mixed_dates(val):
    try:
        num = float(val)
        if num > 1000:
            return pd.to_datetime(num, unit='D', origin='1899-12-30')
    except (ValueError, TypeError):
        pass
    
    return pd.to_datetime(val, dayfirst=True, errors='coerce')

accident_all['วันที่เกิดเหตุ'] = accident_all['วันที่เกิดเหตุ'].apply(parse_mixed_dates)

C:\Users\Asus\AppData\Local\Temp\ipykernel_14280\1080112839.py:9: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(val, dayfirst=True, errors='coerce')

In [34]:
print("วันที่เก่าสุด:", accident_all['วันที่เกิดเหตุ'].min())
print("วันที่ล่าสุด:", accident_all['วันที่เกิดเหตุ'].max())

วันที่เก่าสุด: 2021-01-01 00:00:00
วันที่ล่าสุด: 2025-12-31 00:00:00

In [35]:
print("Type:", accident_all['วันที่เกิดเหตุ'].dtype)

Type: datetime64[ns]

In [38]:
print("Dtype:", df['เวลา'].dtype)
print(df['เวลา'].tail(5))

Dtype: object
23710    23:15
23711    23:20
23712    23:25
23713    23:30
23714    23:55
Name: เวลา, dtype: object

In [42]:
accident_all.to_csv('accident_cleaned.csv', index=False, encoding='utf-8-sig')
print("บันทึกไฟล์ accident_cleaned.csv สำเร็จแล้ว!")

บันทึกไฟล์ accident_cleaned.csv สำเร็จแล้ว!

In [6]:
import pandas as pd
import geopandas as gpd

In [2]:
df1 = pd.read_csv('new_accident.csv')
df1.head(5)

,agency,road_name,province,vehicle,location_type,presumed_cause,incident_type,weather,latitude,longitude,...,year,month,day,is_weekend,time_period,severity_level,is_new_year,is_songkran,is_dangerouse_7days,day_type
0,กรมทางหลวง,ร้อยเอ็ด - หนองดง,ร้อยเอ็ด,รถปิคอัพบรรทุก 4 ล้อ,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,แจ่มใส,16.099711,103.799555,...,2021,1,1,0,ดึก (00:00 - 03:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year
1,กรมทางหลวงชนบท,แยกทางหลวงหมายเลข 223 (กม.ที่ 11+000) - บ้านด่...,สกลนคร,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,ไม่ระบุ,แจ่มใส,17.094963,104.197741,...,2021,1,1,0,ดึก (00:00 - 03:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year
2,กรมทางหลวงชนบท,แยกทางหลวงหมายเลข 212 (กม.ที่ 70+535) - บ้านบา...,มุกดาหาร,รถจักรยานยนต์,ทางสามแยก (Y),เมาสุรา,ไม่ระบุ,แจ่มใส,16.774523,104.737438,...,2021,1,1,0,ดึก (00:00 - 03:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year
3,กรมทางหลวง,ทางรอบเกาะสมุย,สุราษฎร์ธานี,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,ชนท้าย,แจ่มใส,9.559068,100.025668,...,2021,1,1,0,ดึก (00:00 - 03:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year
4,กรมทางหลวง,น้ำคลาด - ปางหมิ่น,พิษณุโลก,รถจักรยานยนต์,ทางโค้งกว้าง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางโค้ง,แจ่มใส,17.297256,100.408688,...,2021,1,1,0,ดึก (00:00 - 03:59),รุนแรงมาก (เสียชีวิต),1,0,1,new_year

In [7]:
tambon = gpd.read_file("subdistricts.geojson")

In [9]:
points = gpd.GeoDataFrame(
    df1,
    geometry=gpd.points_from_xy(
        df1["longitude"],
        df1["latitude"]
    ),
    crs="EPSG:4326"
)

In [10]:
print(points.crs)
print(tambon.crs)

EPSG:4326
EPSG:4326

In [30]:
result = gpd.sjoin(
    points,
    tambon,
    how="left",
    predicate="intersects"
)

In [31]:
result[["latitude", "longitude", "tam_th", "amp_th", "pro_th"]].head()

    latitude   longitude      tam_th       amp_th        pro_th
0  16.099711  103.799555    ธวัชบุรี     ธวัชบุรี      ร้อยเอ็ด
1  17.094963  104.197741  เหล่าปอแดง  เมืองสกลนคร        สกลนคร
2  16.774523  104.737438      ป่งขาม     ว่านใหญ่      มุกดาหาร
3   9.559068  100.025668      บ่อผุด     เกาะสมุย  สุราษฎร์ธานี
4  17.297256  100.408688      บ้านดง   ชาติตระการ      พิษณุโลก

In [35]:
df1.isnull().sum()

agency                  0
road_name               0
province                0
vehicle                 0
location_type           0
presumed_cause          0
incident_type           0
weather                 0
latitude                0
longitude               0
deaths                  0
serious_injuries        0
minor_injuries          0
total_injuries          0
hour                    0
year                    0
month                   0
day                     0
is_weekend              0
time_period             0
severity_level          0
is_new_year             0
is_songkran             0
is_dangerouse_7days     0
day_type                0
tambon                 19
dtype: int64

In [32]:
df1["tambon"] = result["tam_th"].values

In [33]:
df1.to_csv("new_accident.csv", index=False, encoding="utf-8-sig")

In [40]:
df1[df1["tambon"].isna()][
    ["latitude", "longitude", "tambon"]
]

        latitude   longitude tambon
19383  13.158932  102.503823    NaN
20356  13.152920  100.639797    NaN
20605   9.687935  100.046871    NaN
25801   8.200263   98.297465    NaN
35920   7.918515   98.281630    NaN
39286  16.691216   98.517829    NaN
40169   9.576774   99.933169    NaN
47519  15.798669   98.577741    NaN
55224  12.630637  101.495616    NaN
64555   7.650091   99.046282    NaN
69674  11.349792   99.566687    NaN
71568   7.647849   99.045814    NaN
71834  18.520639  103.590168    NaN
72240   7.916175   98.285755    NaN
76040   7.915988   98.291805    NaN
77853   9.496388  100.060511    NaN
88266  16.578241  104.740530    NaN
95578  17.639622  105.176297    NaN
99532  15.301694   98.386987    NaN

In [42]:
tambon_manual = {
    19383: "คลองน้ำใส",
    20356: "ลานตากฟ้า",
    20605: "บ้านใต้",
    25801: "โคกกลอย",
    35920: "ป่าตอง",
    39286: "ท่าสายลวด",
    40169: "แม่น้ำ",
    47519: "แม่จัน",
    55224: "แกลง",
    64555: "เกาะลันตาน้อย",
    69674: "ธงชัย",
    71568: "เกาะลันตาน้อย",
    71834: "ศรีชมภู",
    72240: "ป่าตอง",
    76040: "ป่าตอง",
    77853: "บ่อผุด",
    88266: "มุกดาหาร",
    95578: "โนนตาล",
    99532: "หนองลู"
}

for idx, name in tambon_manual.items():
    df1.loc[idx, "tambon"] = name

,agency,road_name,province,vehicle,location_type,presumed_cause,incident_type,weather,latitude,longitude,...,month,day,is_weekend,time_period,severity_level,is_new_year,is_songkran,is_dangerouse_7days,day_type,tambon
0,กรมทางหลวง,ร้อยเอ็ด - หนองดง,ร้อยเอ็ด,รถปิคอัพบรรทุก 4 ล้อ,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,แจ่มใส,16.099711,103.799555,...,1,1,0,ดึก (00:00 - 03:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year,ธวัชบุรี
1,กรมทางหลวงชนบท,แยกทางหลวงหมายเลข 223 (กม.ที่ 11+000) - บ้านด่...,สกลนคร,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,เมาสุรา,ไม่ระบุ,แจ่มใส,17.094963,104.197741,...,1,1,0,ดึก (00:00 - 03:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year,เหล่าปอแดง
2,กรมทางหลวงชนบท,แยกทางหลวงหมายเลข 212 (กม.ที่ 70+535) - บ้านบา...,มุกดาหาร,รถจักรยานยนต์,ทางสามแยก (Y),เมาสุรา,ไม่ระบุ,แจ่มใส,16.774523,104.737438,...,1,1,0,ดึก (00:00 - 03:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year,ป่งขาม
3,กรมทางหลวง,ทางรอบเกาะสมุย,สุราษฎร์ธานี,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,ชนท้าย,แจ่มใส,9.559068,100.025668,...,1,1,0,ดึก (00:00 - 03:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year,บ่อผุด
4,กรมทางหลวง,น้ำคลาด - ปางหมิ่น,พิษณุโลก,รถจักรยานยนต์,ทางโค้งกว้าง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางโค้ง,แจ่มใส,17.297256,100.408688,...,1,1,0,ดึก (00:00 - 03:59),รุนแรงมาก (เสียชีวิต),1,0,1,new_year,บ้านดง
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111351,กรมทางหลวงชนบท,แยกทางหลวงหมายเลข 37 (กม.ที่ 46+250) - บ้านหนอ...,ประจวบคีรีขันธ์,รถจักรยานยนต์,ทางสามแยก (T),ขับรถเร็วเกินอัตรากำหนด,ไม่ระบุ,แจ่มใส,12.566206,99.897963,...,12,31,0,กลางคืน (20:00 - 23:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year,หินเหล็กไฟ
111352,กรมทางหลวง,คลองท่อม - นาวง,กระบี่,รถปิคอัพบรรทุก 4 ล้อ,ทางโค้งกว้าง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,แจ่มใส,7.899685,99.150610,...,12,31,0,กลางคืน (20:00 - 23:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year,คลองท่อมใต้
111353,กรมทางหลวง,ทางเลี่ยงเมืองมุกดาหาร,มุกดาหาร,รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,แจ่มใส,16.520290,104.698585,...,12,31,0,กลางคืน (20:00 - 23:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year,มุกดาหาร
111354,กรมทางหลวง,กระเทียม - ห้วยสำราญ,สุรินทร์,รถปิคอัพบรรทุก 4 ล้อ,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,แจ่มใส,14.642791,104.037515,...,12,31,0,กลางคืน (20:00 - 23:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year,ตาคง
111355,กรมทางหลวง,เขาวัง - น้ำพุ,ราชบุรี,รถจักรยานยนต์,ทางตรง+ไม่มีความลาดชัน,ขับรถเร็วเกินอัตรากำหนด,พลิกคว่ำ/ตกถนนในทางตรง,แจ่มใส,13.511113,99.721707,...,12,31,0,กลางคืน (20:00 - 23:59),รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย),1,0,1,new_year,ห้วยไผ่

In [45]:
df1.to_csv("new_accident.csv", index=False, encoding="utf-8-sig")

In [49]:
df = pd.read_csv("new_accident.csv")

df["province"] = df["province"].replace(
    {"อยุธยา": "พระนครศรีอยุธยา"}
)

df.to_csv(
    "new_accident.csv",index=False,encoding="utf-8-sig")

In [1]:
import pandas as pd

In [5]:
df2026 = pd.read_csv("accident2026.csv", encoding="utf-8-sig")

In [6]:
df2026.isnull().sum()

ปีที่เกิดเหตุ                                0
วันที่เกิดเหตุ                               0
เวลา                                         0
วันที่รายงาน                                75
เวลาที่รายงาน                               75
หน่วยงาน                                     0
สายทางหน่วยงาน                               0
รหัสสายทาง                                   0
สายทาง                                      24
ก.ม.                                       149
จังหวัด                                      1
รถคันที่1                                  379
บริเวณที่เกิดเหตุ/ลักษณะทาง               1535
บริเวณที่เกิดเหตุอื่น                      478
มูลเหตุสันนิษฐาน                           522
ลักษณะการเกิดอุบัติเหตุ                    981
สภาพอากาศ                                  144
LATITUDE                                   151
LONGITUDE                                  151
จำนวนรถที่เกิดเหตุ(รวมคันที่1)               0
จำนวนที่เกิดเหตุทั้งหมด(รวมคนเดินเท้า)       0
รถจักรยานยนต์                                0
รถสามล้อเครื่อง                              0
รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ        0
รถตู้                                        0
รถปิคอัพโดยสาร                               0
รถโดยสารมากกว่า4ล้อ                          0
รถปิคอัพบรรทุก4ล้อ                           0
รถบรรทุก6ล้อ                                 0
รถบรรทุกมากกว่า6ล้อไม่เกิน10ล้อ              0
รถบรรทุกมากกว่า10ล้อ(รถพ่วง)                 0
รถอีแต๋น                                     0
อื่นๆ                                        0
คนเดินเท้า                                   0
จำนวนผู้เสียชีวิต                            0
จำนวนผู้บาดเจ็บสาหัส                         0
จำนวนผู้บาดเจ็บเล็กน้อย                      0
รวมจำนวนผู้บาดเจ็บ                           0
dtype: int64

In [7]:
print("Duplicate:", df2026.duplicated().sum())

Duplicate: 22

In [8]:
sorted(df2026["จังหวัด"].dropna().unique())

['กระบี่',
 'กรุงเทพมหานคร',
 'กาญจนบุรี',
 'กาฬสินธุ์',
 'กำแพงเพชร',
 'ขอนแก่น',
 'จันทบุรี',
 'ฉะเชิงเทรา',
 'ชลบุรี',
 'ชัยนาท',
 'ชัยภูมิ',
 'ชุมพร',
 'ตรัง',
 'ตราด',
 'ตาก',
 'นครนายก',
 'นครปฐม',
 'นครพนม',
 'นครราชสีมา',
 'นครศรีธรรมราช',
 'นครสวรรค์',
 'นนทบุรี',
 'นราธิวาส',
 'น่าน',
 'บึงกาฬ',
 'บุรีรัมย์',
 'ปทุมธานี',
 'ประจวบคีรีขันธ์',
 'ปราจีนบุรี',
 'ปัตตานี',
 'พระนครศรีอยุธยา',
 'พะเยา',
 'พังงา',
 'พัทลุง',
 'พิจิตร',
 'พิษณุโลก',
 'ภูเก็ต',
 'มหาสารคาม',
 'มุกดาหาร',
 'ยะลา',
 'ยโสธร',
 'ระนอง',
 'ระยอง',
 'ราชบุรี',
 'ร้อยเอ็ด',
 'ลพบุรี',
 'ลำปาง',
 'ลำพูน',
 'ศรีสะเกษ',
 'สกลนคร',
 'สงขลา',
 'สตูล',
 'สมุทรปราการ',
 'สมุทรสงคราม',
 'สมุทรสาคร',
 'สระบุรี',
 'สระแก้ว',
 'สิงห์บุรี',
 'สุพรรณบุรี',
 'สุราษฎร์ธานี',
 'สุรินทร์',
 'สุโขทัย',
 'หนองคาย',
 'หนองบัวลำภู',
 'อยุธยา',
 'อำนาจเจริญ',
 'อุดรธานี',
 'อุตรดิตถ์',
 'อุทัยธานี',
 'อุบลราชธานี',
 'อ่างทอง',
 'เชียงราย',
 'เชียงใหม่',
 'เพชรบุรี',
 'เพชรบูรณ์',
 'เลย',
 'แพร่',
 'แม่ฮ่องสอน']

In [9]:
df2026["สภาพอากาศ"].value_counts(dropna=False)

สภาพอากาศ
แจ่มใส                           13652
ฝนตก                              1385
NaN                                144
มีหมอก/ควัน/ฝุ่น                    29
มืดครึ้ม                            17
อื่นๆ                                7
ภัยธรรมชาติ เช่น พายุ น้ำท่วม        5
Name: count, dtype: int64

In [10]:
df2026["มูลเหตุสันนิษฐาน"] = df2026["มูลเหตุสันนิษฐาน"].replace({

    "ขับขี่ย้อนศร": "ขับรถย้อนศร",

    "ขับชิดซ้ายมากเกินไป": "ขับรถชิดซ้ายมากเกินไป",

    "ขับรถกระชั้นชิด": "ขับรถตามกระชั้นชิด",

    "ฝ่าฝืนสัญญาณไฟ / เครื่องหมายจราจร": "ฝ่าฝืนสัญญาณไฟ/เครื่องหมายจราจร",

    "ฝ่าฝืนป้ายหยุดขณะออกจากทางร่วมทางแยก": "ฝ่าฝืนป้ายหยุดขณะออกจากทางร่วมแยก",

    "มึนเมาจากแอลกอฮอล์": "เมาสุรา",

    "รถเสียไม่แสดงเครื่องหมาย/สัญญาณตามที่กำหนด":
        "รถเสียไม่แสดงเครื่องหมายหรือสัญญาณไฟที่กำหนด",

    "ระบบไฟฟ้ขัดข้อง": "ระบบไฟฟ้าขัดข้อง",
    "ระบบไฟฟ้าของยานพาหนะขัดข้อง": "ระบบไฟฟ้าขัดข้อง",

    "อาการป่วย หรือการไร้ความสามารถทางประสาทหรือร่างกาย":
        "อาการป่วยหรือการไร้ความสามารถทางประสาทหรือร่างกาย",

    "ใช้โทรศัพท์เคลื่อนที่ขณะขับรถ": "ใช้โทรศัพท์ขณะขับรถ",

    "ไม่ให้สัญญาณชะลอ / เลี้ยว": "ไม่ให้สัญญาณชะลอ/เลี้ยว",

    "ไม่ให้สัญญาณเข้าจอด หรือออกจากที่จอด":
        "ไม่ให้สัญญาณเข้าจอด/ออกจากที่จอด",

    "ไม่คุ้นเคยกับการขับขี่ด้านซ้าย เช่น กรณีชาวต่างชาติ":
        "ไม่คุ้นเคยกับการขับขี่ด้านซ้าย",

    "เบรคกะทันหัน": "เบรกกะทันหัน",
    
    "เบรคกระทันหัน": "เบรกกะทันหัน",
    
    "เบครกระทันหัน": "เบรกกะทันหัน",

    "ถนนลื่น (เนื่องจากสภาพอากาศ)": "ถนนลื่น",

    "มีสิ่งรบกวนภายในรถ เช่น มีเด็ก มีสัตว์ภายในรถ":
        "มีสิ่งรบกวนภายในรถ",

    "แสงสว่างไม่เพียงพอหรือทัศนวิสัยกลางคืนไม่ดี":
        "แสงสว่างไม่เพียงพอ",

    "เข้าผิดช่องทางผิด": "เข้าผิดช่อง",

    "ไม่คุ้นชินกับยานพาหนะ เช่น กรณีเช่ารถ":
        "ไม่คุ้นเคยเส้นทาง/ขับรถไม่ชำนาญ",
    
     "อุปกรณ์ยานพาหนะบกพร่อง (ระบุ)": "อุปกรณ์ยานพาหนะบกพร่อง"
})

In [11]:
for value in sorted(df2026["มูลเหตุสันนิษฐาน"].dropna().unique()):
    print(value)

การกระทำที่สุ่มเสี่ยงบนถนน
การซ่อม/สร้างบนสายทาง
ขับขี่ช้าเกินเนื่องจากลักษณะของยานพาหนะ (เช่น แทรคเตอร์)
ขับรถคร่อมเส้นแบ่งทิศทาง
ขับรถตามกระชั้นชิด
ขับรถผิดช่องทาง
ขับรถย้อนศร
ขับรถเร็วเกินอัตรากำหนด
ขับรถไม่เปิดไฟ/ไม่ใช้แสงสว่างตามกำหนด
ข้ามถนนโดยมีรถจอดหรือวัตถุข้างทางบดบังผู้ขับขี่
คน/รถ/สัตว์ตัดหน้ากระชั้นชิด
ความต่างระดับของไหล่ทางกับผิวทาง
ความประมาท/เร่งรีบ (วิ่งตัดหน้า)
ถนนชำรุด
ถนนลื่น
ทางโค้งอันตราย
บรรทุกเกินอัตรา
ฝ่าฝืนป้ายหยุดขณะออกจากทางร่วมแยก
ฝ่าฝืนสัญญาณไฟ/เครื่องหมายจราจร
มีกองวัสดุ/สิ่งกีดขวาง
มีสิ่งบดบังการมองเห็น
มีสิ่งรบกวนภายนอกรถ
มีสิ่งรบกวนภายในรถ
ยางเสื่อมสภาพ/ยางแตก
รถเสียไม่แสดงเครื่องหมายหรือสัญญาณไฟที่กำหนด
ระบบบังคับเลี้ยวขัดข้อง
ระบบสัญญาณไฟจราจรขัดข้อง
ระบบห้ามล้อขัดข้อง/ระบบเบรกชำรุด
ระบบไฟฟ้าขัดข้อง
ระยะการมองเห็นไม่เพียงพอ
สูญเสียการควบคุม
หลับใน
อาการป่วยหรือการไร้ความสามารถทางประสาทหรือร่างกาย
อุปกรณ์ยานพาหนะบกพร่อง
เปลี่ยนช่องทางกะทันหัน
เมาสุรา
แซงรถอย่างผิดกฎหมาย
แสงสว่างไม่เพียงพอ
โรคประจำตัว
ใช้โทรศัพท์ขณะขับรถ
ไม่คุ้นเคยกับการขับขี่ด้านซ้าย
ไม่คุ้นเคยเส้นทาง/ขับรถไม่ชำนาญ
ไม่ยอมให้รถที่มีสิทธิ์ไปก่อน
ไม่ให้สัญญาณชะลอ/เลี้ยว
ไม่ให้สัญญาณเข้าจอด/ออกจากที่จอด

In [12]:
df2026['LATITUDE'] = pd.to_numeric(df2026['LATITUDE'], errors='coerce')
df2026['LONGITUDE'] = pd.to_numeric(df2026['LONGITUDE'], errors='coerce')

In [13]:
valid_lat = (df2026['LATITUDE'] >= 5.0) & (df2026['LATITUDE'] <= 21.0)
valid_long = (df2026['LONGITUDE'] >= 97.0) & (df2026['LONGITUDE'] <= 106.0)

In [14]:
df2026 = df2026[valid_lat & valid_long].copy()

In [15]:
text_cols = [
    'บริเวณที่เกิดเหตุ', 'มูลเหตุสันนิษฐาน', 'ลักษณะการเกิดเหตุ', 
    'สภาพอากาศ', 'จังหวัด', 'รถคันที่1', 'สายทาง'
]

for col in text_cols:
    if col in df2026.columns:
        df2026[col] = df2026[col].fillna('ไม่ระบุ').astype(str).str.strip()

In [16]:
df2026['ชั่วโมง'] = df2026['เวลา'].astype(str).str.extract(r'(\d+)')[0]
df2026['ชั่วโมง'] = pd.to_numeric(df2026['ชั่วโมง'], errors='coerce')

df2026['ชั่วโมง'] = df2026['ชั่วโมง'].fillna(-1).astype(int)

In [17]:
def clean_time_str(val):
    if pd.isna(val):
        return val
    try:
        v = float(val)
        if 0 <= v <= 1:
            total_sec = int(v * 86400)
            return f"{total_sec // 3600:02d}:{(total_sec % 3600) // 60:02d}"
    except ValueError:
        pass
    return str(val).strip()

df2026['เวลา'] = df2026['เวลา'].apply(clean_time_str)
df2026['ชั่วโมง'] = df2026['เวลา'].str.extract(r'^(\d{1,2}):')[0]
df2026['ชั่วโมง'] = pd.to_numeric(df2026['ชั่วโมง'], errors='coerce')
df2026['ชั่วโมง'] = df2026['ชั่วโมง'].fillna(-1).astype(int)

In [24]:
def parse_mixed_dates(val):
    try:
        num = float(val)
        if num > 1000:
            return pd.to_datetime(num, unit='D', origin='1899-12-30')
    except (ValueError, TypeError):
        pass
    
    return pd.to_datetime(val, dayfirst=True, errors='coerce')

df2026['วันที่เกิดเหตุ'] = df2026['วันที่เกิดเหตุ'].apply(parse_mixed_dates)

In [25]:
df2026["วันที่เกิดเหตุ"] = df2026["วันที่เกิดเหตุ"].apply(parse_mixed_dates)

df2026["year"] = df2026["วันที่เกิดเหตุ"].dt.year
df2026["month"] = df2026["วันที่เกิดเหตุ"].dt.month
df2026["day"] = df2026["วันที่เกิดเหตุ"].dt.day
df2026["dayofweek"] = df2026["วันที่เกิดเหตุ"].dt.dayofweek
df2026["is_weekend"] = df2026["dayofweek"].isin([5, 6]).astype(int)

In [28]:
print("วันที่เก่าสุด:", df2026['วันที่เกิดเหตุ'].min())
print("วันที่ล่าสุด:", df2026['วันที่เกิดเหตุ'].max())

วันที่เก่าสุด: 2026-01-01 00:00:00
วันที่ล่าสุด: 2026-09-07 00:00:00

In [29]:
def get_time_period(ชั่วโมง):
    if pd.isna(ชั่วโมง):
        return 'ไม่ระบุ'
    elif 0 <= ชั่วโมง < 4:
        return 'ดึก (00:00 - 03:59)'
    elif 4 <= ชั่วโมง < 8:
        return 'เช้ามืด (04:00 - 07:59)'
    elif 8 <= ชั่วโมง < 12:
        return 'เช้า (08:00 - 11:59)'
    elif 12 <= ชั่วโมง < 16:
        return 'บ่าย (12:00 - 15:59)'
    elif 16 <= ชั่วโมง < 20:
        return 'เย็น (16:00 - 19:59)'
    else:
        return 'กลางคืน (20:00 - 23:59)'

In [30]:
df2026['time_period'] = df2026['ชั่วโมง'].apply(get_time_period)

In [31]:
print("ชั่วโมงต่ำสุด:", df2026['ชั่วโมง'].min())
print("ชั่วโมงสูงสุด:", df2026['ชั่วโมง'].max())

invalid_hours = df2026[(df2026['ชั่วโมง'] < 0) | (df2026['ชั่วโมง'] > 23)]
print("จำนวนแถวที่ค่าชั่วโมงผิดปกติ:", len(invalid_hours))

ชั่วโมงต่ำสุด: 0
ชั่วโมงสูงสุด: 23
จำนวนแถวที่ค่าชั่วโมงผิดปกติ: 0

In [32]:
missing_hours = df2026['ชั่วโมง'].isna().sum()
print("จำนวนค่าว่างในชั่วโมง:", missing_hours)

จำนวนค่าว่างในชั่วโมง: 0

In [33]:
print(df2026['time_period'].value_counts(dropna=False))

time_period
บ่าย (12:00 - 15:59)       3077
เย็น (16:00 - 19:59)       3030
เช้า (08:00 - 11:59)       2925
เช้ามืด (04:00 - 07:59)    2198
กลางคืน (20:00 - 23:59)    2047
ดึก (00:00 - 03:59)        1811
Name: count, dtype: int64

In [34]:
def calculate_severity(row):
    if row['จำนวนผู้เสียชีวิต'] >= 1:
        return 'รุนแรงมาก (เสียชีวิต)'
    elif row['จำนวนผู้บาดเจ็บสาหัส'] >= 1:
        return 'รุนแรงปานกลาง (บาดเจ็บสาหัส)'
    else:
        return 'รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย)'

df2026['severity_level'] = df2026.apply(calculate_severity, axis=1)

In [35]:
print(df2026['severity_level'].value_counts())

print("\n--- สัดส่วน (%) ---")
print(df2026['severity_level'].value_counts(normalize=True) * 100)

severity_level
รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย)    12440
รุนแรงมาก (เสียชีวิต)                             1535
รุนแรงปานกลาง (บาดเจ็บสาหัส)                      1113
Name: count, dtype: int64

--- สัดส่วน (%) ---
severity_level
รุนแรงน้อย (บาดเจ็บเล็กน้อย/ทรัพย์สินเสียหาย)    82.449629
รุนแรงมาก (เสียชีวิต)                            10.173648
รุนแรงปานกลาง (บาดเจ็บสาหัส)                      7.376723
Name: proportion, dtype: float64

In [36]:
def check_new_year(date):
    if pd.isna(date): return 0
    return 1 if (date.month == 12 and date.day >= 29) or (date.month == 1 and date.day <= 4) else 0

def check_songkran(date):
    if pd.isna(date): return 0
    return 1 if (date.month == 4 and 11 <= date.day <= 17) else 0

df2026['is_new_year'] = df2026['วันที่เกิดเหตุ'].apply(check_new_year)
df2026['is_songkran'] = df2026['วันที่เกิดเหตุ'].apply(check_songkran)
df2026['is_dangerous_7days'] = ((df2026['is_new_year'] == 1) | (df2026['is_songkran'] == 1)).astype(int)

print("ปีใหม่     :", df2026['is_new_year'].sum(), "เคส")
print("สงกรานต์  :", df2026['is_songkran'].sum(), "เคส")
print("รวม 7วันอันตราย:", df2026['is_dangerous_7days'].sum(), "เคส")

ปีใหม่     : 871 เคส
สงกรานต์  : 1185 เคส
รวม 7วันอันตราย: 2056 เคส

In [158]:
drop_cols = [
    "บริเวณที่เกิดเหตุ/ลักษณะทาง",
    "ลักษณะการเกิดอุบัติเหตุ",
    "บริเวณที่เกิดเหตุอื่น",
    "ก.ม.",
    "วันที่รายงาน",
    "เวลาที่รายงาน",
    "รถคันที่1",
    "จำนวนรถที่เกิดเหตุ(รวมคันที่1)",
    "จำนวนที่เกิดเหตุทั้งหมด(รวมคนเดินเท้า)",
    "รถจักรยานยนต์",
    "รถสามล้อเครื่อง",
    "รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ",
    "รถตู้",
    "รถปิคอัพโดยสาร",
    "รถโดยสารมากกว่า4ล้อ",
    "รถปิคอัพบรรทุก4ล้อ",
    "รถบรรทุก6ล้อ",
    "รถบรรทุกมากกว่า6ล้อไม่เกิน10ล้อ",
    "รถบรรทุกมากกว่า10ล้อ(รถพ่วง)",
    "รถอีแต๋น",
    "อื่นๆ",
    "คนเดินเท้า",
    "สายทางหน่วยงาน",
    "รหัสสายทาง",
    "สายทาง",
    "เวลา",
]

df2026_cleaned = df2026.drop(
    columns=[col for col in drop_cols if col in df2026.columns]
)

df2026_cleaned.to_csv(
    "accident2026_cleaned.csv", index=False, encoding="utf-8-sig"
)

In [159]:
new2026 = pd.read_csv("accident2026_cleaned.csv")

In [160]:
column_mapping = {
    'หน่วยงาน': 'agency',
    'จังหวัด': 'province',
    'มูลเหตุสันนิษฐาน': 'presumed_cause',
    'สภาพอากาศ': 'weather',
    'จำนวนผู้เสียชีวิต': 'deaths',
    'จำนวนผู้บาดเจ็บสาหัส': 'serious_injuries',
    'จำนวนผู้บาดเจ็บเล็กน้อย': 'minor_injuries',
    'รวมจำนวนผู้บาดเจ็บ': 'total_injuries',
    'ชั่วโมง': 'hour',
    'LATITUDE' : 'latitude',
    'LONGITUDE' : 'longitude',
    'is_dangerous_7days' : 'is_dangerouse_7days'
}
df2 = new2026.rename(columns=column_mapping)

In [161]:
conditions = [
    df2["is_songkran"] == 1,
    df2["is_new_year"] == 1,
    df2["is_dangerouse_7days"] == 1,
    df2["is_weekend"] == 1,
]
choices = ["songkran", "new_year", "danger_7days", "weekend"]

In [162]:
df2["day_type"] = np.select(conditions, choices, default="normal_day")

In [163]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15088 entries, 0 to 15087
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ปีที่เกิดเหตุ        15088 non-null  int64
 1   วันที่เกิดเหตุ       15088 non-null  object
 2   agency               15088 non-null  object
 3   province             15088 non-null  object
 4   presumed_cause       15088 non-null  object
 5   weather              15088 non-null  object
 6   latitude             15088 non-null  float64
 7   longitude            15088 non-null  float64
 8   deaths               15088 non-null  int64
 9   serious_injuries     15088 non-null  int64
 10  minor_injuries       15088 non-null  int64
 11  total_injuries       15088 non-null  int64
 12  hour                 15088 non-null  int64
 13  year                 15088 non-null  int64
 14  month                15088 non-null  int64
 15  day                  15088 non-null  int64
 16  dayofweek            15088 non-null  int64
 17  is_weekend           15088 non-null  int64
 18  time_period          15088 non-null  object
 19  severity_level       15088 non-null  object
 20  is_new_year          15088 non-null  int64
 21  is_songkran          15088 non-null  int64
 22  is_dangerouse_7days  15088 non-null  int64
 23  day_type             15088 non-null  object
dtypes: float64(2), int64(14), object(8)
memory usage: 2.8+ MB

In [164]:
df2.to_csv('accident2026_cleaned.csv', index=False, encoding='utf-8-sig')

print("บันทึกแล้ว")

บันทึกแล้ว

In [165]:
df3 = pd.read_csv("accident2026_cleaned.csv")

In [166]:
import geopandas as gpd
tambon = gpd.read_file("subdistricts.geojson")

In [167]:
points = gpd.GeoDataFrame(
    df3,
    geometry=gpd.points_from_xy(
        df3["longitude"],
        df3["latitude"]
    ),
    crs="EPSG:4326"
)

In [168]:
result = gpd.sjoin(
    points,
    tambon,
    how="left",
    predicate="intersects"
)

In [169]:
result[["latitude", "longitude", "tam_th", "amp_th", "pro_th"]].head()

    latitude   longitude       tam_th       amp_th           pro_th
0  16.381335  104.544672  นิคมคำสร้อย  นิคมคำสร้อย         มุกดาหาร
1  14.853079  101.578627      คลองไผ่       สีคิ้ว       นครราชสีมา
2  19.089352   98.989752     แม่หอพระ       แม่แตง        เชียงใหม่
3  14.324264  100.652160       คานหาม        อุทัย  พระนครศรีอยุธยา
4   6.676034  101.128955     นาประดู่     โคกโพธิ์          ปัตตานี

In [170]:
df3["tambon"] = result["tam_th"].values

In [171]:
df3.isnull().sum()

ปีที่เกิดเหตุ          0
วันที่เกิดเหตุ         0
agency                 0
province               0
presumed_cause         0
weather                0
latitude               0
longitude              0
deaths                 0
serious_injuries       0
minor_injuries         0
total_injuries         0
hour                   0
year                   0
month                  0
day                    0
dayofweek              0
is_weekend             0
time_period            0
severity_level         0
is_new_year            0
is_songkran            0
is_dangerouse_7days    0
day_type               0
tambon                 1
dtype: int64

In [172]:
df3.to_csv('accident2026_cleaned2.csv', index=False, encoding='utf-8-sig')

print("บันทึกแล้ว")

บันทึกแล้ว

In [173]:
import pandas as pd

df_raw = pd.read_csv("accident2026_cleaned2.csv", encoding="utf-8-sig")

fix_csv_words = {
    "บ้านน้อยซุ้มขี้เ": "บ้านน้อยซุ้มขี้เหล็ก",
    "บ้านน้อยซุ้มขี้": "บ้านน้อยซุ้มขี้เหล็ก",
    "นิคมทุ่งโพธิ์ทะเ": "นิคมทุ่งโพธิ์ทะเล",
    "ศรีษะจรเข้น้อย": "ศีรษะจรเข้น้อย",
    "กะลาเส": "กะลาเสะ",
    "โนนศิลาเลิง": "โนนศิลาเลิง",
    "สุไหงโก-ลก": "สุไหงโกลก",
    "เทศบาลเมืองพระประแดง": "ตลาด",
    "เทศบาลเมืองพระปร": "ตลาด",
    "เทศบาลเมืองทุ่งสง": "ปากแพรก",
    "เทศบาลเมืองทุ่งส": "ปากแพรก",
    "เทศบาลนครสมุทรปราการ": "ปากน้ำ",
    "เทศบาลนครสมุทรปร": "ปากน้ำ",
    "เขตการปกครองพิเศษพัทยา": "หนองปรือ",
    "เขตการปกคองพิเศษ": "หนองปรือ",
    "ปากพนังฝั่งตะวันออก": "ปากพนังฝั่งตะวันออก",
    "ปากพนังฝั่งตะวัน": "ปากพนังฝั่งตะวันออก",
    "นิคมสร้างตนเอง": "พุกร่าง",
    "บางมด": "บางมด",
    "บางน้ำจืด": "บางน้ำจืด",
}

if "tambon" in df_raw.columns:
    df_raw["tambon"] = df_raw["tambon"].replace(fix_csv_words)
elif "ตำบล" in df_raw.columns:
    df_raw["ตำบล"] = df_raw["ตำบล"].replace(fix_csv_words)

df_raw.to_csv("new_accident2026.csv", index=False, encoding="utf-8-sig")
print("new_accident2026.csv")

new_accident2026.csv

In [174]:
df4 = pd.read_csv("new_accident2026.csv")

In [175]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:12345@localhost:3306/accident_db_dump"
)

df_2026 = pd.read_csv("new_accident2026.csv")

provinces_db = pd.read_sql(
    """
    SELECT province_code, pro_name_th
    FROM provinces
    """,
    engine,
)

subdistricts_db = pd.read_sql(
    """
    SELECT code, name_in_thai
    FROM subdistricts
    """,
    engine,
)

df_2026["province_clean"] = df_2026["province"].astype("string").str.strip()

provinces_db["province_clean"] = (
    provinces_db["pro_name_th"].astype("string").str.strip()
)

province_alias = {"อยุธยา": "พระนครศรีอยุธยา"}
df_2026["province_clean"] = df_2026["province_clean"].replace(province_alias)

df_2026 = df_2026.merge(
    provinces_db[["province_code", "province_clean"]],
    on="province_clean",
    how="left",
)

df_2026["province_code"] = pd.to_numeric(
    df_2026["province_code"], errors="coerce"
)

fix_words = {
    "นิคมทุ่งโพธิ์ทะเ": "นิคมทุ่งโพธิ์ทะเล",
    "บ้านน้อยซุ้มขี้": "บ้านน้อยซุ้มขี้เหล็ก",
    "บ้านน้อยซุ้มขี้เ": "บ้านน้อยซุ้มขี้เหล็ก",
}
df_2026["tambon"] = df_2026["tambon"].replace(fix_words)

subdistricts_db["code"] = (
    subdistricts_db["code"].astype("string").str.strip().str.zfill(6)
)

subdistricts_db["province_code"] = pd.to_numeric(
    subdistricts_db["code"].str[:2], errors="coerce"
)
subdistricts_db["district_code"] = pd.to_numeric(
    subdistricts_db["code"].str[:4], errors="coerce"
)
subdistricts_db["subdistrict_code"] = pd.to_numeric(
    subdistricts_db["code"], errors="coerce"
)

subdistricts_db["tambon_clean"] = (
    subdistricts_db["name_in_thai"]
    .astype("string")
    .str.strip()
    .str.replace(r"^ต\.", "", regex=True)
    .str.replace(r"^ตำบล", "", regex=True)
    .str.replace("-", "", regex=False)
    .str.strip()
)

df_2026["tambon_clean"] = (
    df_2026["tambon"]
    .astype("string")
    .str.strip()
    .str.replace(r"^ต\.", "", regex=True)
    .str.replace(r"^ตำบล", "", regex=True)
    .str.replace("-", "", regex=False)
    .str.strip()
)

subdistricts_db = subdistricts_db[
    [
        "province_code",
        "district_code",
        "subdistrict_code",
        "tambon_clean",
    ]
].drop_duplicates()

df_2026 = df_2026.merge(
    subdistricts_db,
    on=["province_code", "tambon_clean"],
    how="left",
)

df_2026["case_severity_score"] = (
    (df_2026["deaths"] * 25)
    + (df_2026["serious_injuries"] * 15)
    + (df_2026["minor_injuries"] * 5)
    + 5
)

df_train_2026 = (
    df_2026.groupby(
        [
            "province_code",
            "district_code",
            "subdistrict_code",
            "time_period",
            "day_type",
            "weather",
            "agency",
            "year",
        ],
        dropna=False,
    )
    .agg(total_severity_score=("case_severity_score", "sum"))
    .reset_index()
)

df_train_2026 = df_train_2026.rename(columns={"agency": "road_agency"})

q95 = df_train_2026["total_severity_score"].quantile(0.95)
min_s = df_train_2026["total_severity_score"].min()

denom = q95 - min_s
if denom == 0:
    denom = 1

clipped_score = df_train_2026["total_severity_score"].clip(upper=q95)

df_train_2026["risk_score"] = 5 + ((clipped_score - min_s) / denom) * 95
df_train_2026["risk_score"] = df_train_2026["risk_score"].round(2)

df_train_2026 = df_train_2026.drop(columns=["total_severity_score"])

df_train_2026.to_sql(
    name="accidents2026",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=5000,
)

print(f"accidents2026 จำนวน {len(df_train_2026):,} แถว")

accidents2026 จำนวน 11,206 แถว

In [176]:
from sqlalchemy import create_engine

engine = create_engine(
    'mysql+pymysql://root:12345@localhost/accident_db_dump'
)

df = pd.read_sql('SELECT * FROM accidents2026', engine)

print(df.isnull().sum())

province_code        0
district_code       55
subdistrict_code    55
time_period          0
day_type             0
weather              0
road_agency          0
year                 0
risk_score           0
dtype: int64

In [2]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine(
    "mysql+pymysql://root:12345@localhost:3306/accident_db_dump"
)

df_2026 = pd.read_csv("new_accident2026.csv")

provinces_db = pd.read_sql(
    """
    SELECT province_code, pro_name_th
    FROM provinces
    """,
    engine
)

subdistricts_db = pd.read_sql(
    """
    SELECT code, name_in_thai
    FROM subdistricts
    """,
    engine
)

df_2026["province_clean"] = (
    df_2026["province"]
    .astype("string")
    .str.strip()
)

provinces_db["province_clean"] = (
    provinces_db["pro_name_th"]
    .astype("string")
    .str.strip()
)

df_2026["province_clean"] = df_2026["province_clean"].replace({
    "อยุธยา": "พระนครศรีอยุธยา"
})

df_2026 = df_2026.merge(
    provinces_db[["province_code", "province_clean"]],
    on="province_clean",
    how="left"
)

df_2026["province_code"] = pd.to_numeric(
    df_2026["province_code"],
    errors="coerce"
)

fix_words = {
    "นิคมทุ่งโพธิ์ทะเ": "นิคมทุ่งโพธิ์ทะเล",
    "บ้านน้อยซุ้มขี้": "บ้านน้อยซุ้มขี้เหล็ก",
    "บ้านน้อยซุ้มขี้เ": "บ้านน้อยซุ้มขี้เหล็ก",
}

df_2026["tambon"] = df_2026["tambon"].replace(fix_words)

subdistricts_db["code"] = (
    subdistricts_db["code"]
    .astype("string")
    .str.strip()
    .str.zfill(6)
)

subdistricts_db["province_code"] = pd.to_numeric(
    subdistricts_db["code"].str[:2],
    errors="coerce"
)

subdistricts_db["district_code"] = pd.to_numeric(
    subdistricts_db["code"].str[:4],
    errors="coerce"
)

subdistricts_db["subdistrict_code"] = pd.to_numeric(
    subdistricts_db["code"],
    errors="coerce"
)

subdistricts_db["tambon_clean"] = (
    subdistricts_db["name_in_thai"]
    .astype("string")
    .str.strip()
    .str.replace(r"^ต\.", "", regex=True)
    .str.replace(r"^ตำบล", "", regex=True)
    .str.replace("-", "", regex=False)
    .str.strip()
)

df_2026["tambon_clean"] = (
    df_2026["tambon"]
    .astype("string")
    .str.strip()
    .str.replace(r"^ต\.", "", regex=True)
    .str.replace(r"^ตำบล", "", regex=True)
    .str.replace("-", "", regex=False)
    .str.strip()
)

subdistricts_db = subdistricts_db[
    [
        "province_code",
        "district_code",
        "subdistrict_code",
        "tambon_clean"
    ]
].drop_duplicates()

df_2026 = df_2026.merge(
    subdistricts_db,
    on=["province_code", "tambon_clean"],
    how="left"
)

df_update = (
    df_2026.groupby(
        [
            "province_code",
            "district_code",
            "subdistrict_code",
            "time_period",
            "day_type",
            "weather",
            "agency",
            "year"
        ],
        dropna=False
    )
    .agg(
        deaths=("deaths", "sum"),
        serious_injuries=("serious_injuries", "sum"),
        minor_injuries=("minor_injuries", "sum")
    )
    .reset_index()
)

df_update = df_update.rename(
    columns={"agency": "road_agency"}
)

db_data = pd.read_sql(
    """
    SELECT
        id,
        province_code,
        district_code,
        subdistrict_code,
        time_period,
        day_type,
        weather,
        road_agency,
        year
    FROM accidents2026
    """,
    engine
)

merge_cols = [
    "province_code",
    "district_code",
    "subdistrict_code",
    "time_period",
    "day_type",
    "weather",
    "road_agency",
    "year"
]

df_update["province_code"] = df_update["province_code"].astype("Int64")
df_update["district_code"] = df_update["district_code"].astype("Int64")
df_update["subdistrict_code"] = df_update["subdistrict_code"].astype("Int64")

db_data["province_code"] = db_data["province_code"].astype("Int64")
db_data["district_code"] = db_data["district_code"].astype("Int64")
db_data["subdistrict_code"] = db_data["subdistrict_code"].astype("Int64")

df_update = df_update.merge(
    db_data,
    on=merge_cols,
    how="left"
)

df_update = df_update.dropna(subset=["id"])

update_sql = text("""
UPDATE accidents2026
SET
    deaths = :deaths,
    serious_injuries = :serious_injuries,
    minor_injuries = :minor_injuries
WHERE id = :id
""")

updated = 0

with engine.begin() as conn:
    for _, row in df_update.iterrows():
        result = conn.execute(
            update_sql,
            {
                "id": int(row["id"]),
                "deaths": int(row["deaths"]),
                "serious_injuries": int(row["serious_injuries"]),
                "minor_injuries": int(row["minor_injuries"])
            }
        )

        updated += result.rowcount

print("อัปเดตข้อมูลเรียบร้อย")
print(f"จำนวนแถวที่อัปเดต: {updated:,}")

อัปเดตข้อมูลเรียบร้อย
จำนวนแถวที่อัปเดต: 11,151